project:
  type: website

website:
  favicon: favicon.webp
  open-graph: true
  site-url: https://github.com/aisicresearch
  search: false
  navbar:
    logo: images/logo.png
    logo-alt: "logo"
    title: ""
    collapse-below: lg
    right: 
      - text: ARTICLES
        href: articles/index.qmd
      - text: ABOUT
        href: about.qmd
      - text: CONTACT
        href: contact.qmd
      - text: DE ðŸ‡©ðŸ‡ª
        href: /de/index.qmd


  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    center:
      - href: https://github.com/aisicresearch
        icon: github
        aria-label: GitHub
      - href: imprint.html
        text: Imprint
      - href: privacy-statement.html
        text: Privacy Statement
    left:
      - text: "Â© 2025 AI-SIC"
    right:
      - text: "Built with Quarto, inspired by martenw.com"

format:
  html:
    theme: [aisic-custom.scss]
    toc: true
    grid:
      body-width: 800px
    html-math-method: katex
    include-in-header: 
      text: |
        <script type="application/ld+json"> # JSON-LD for SEO
        {
          "@context": "https://schema.org/",
          "@type": "Organization",
          "name": "AI-SIC",
          "url": "https://github.com/aisicresearch",
          "alternateName": "AI Enhanced Validation of Survey Instruments",
          "description": "Research Project",
          "image": "",
          "sameAs": [
             "https://github.com/aisicresearch"
          ],
        }
        </script>


#for transparency in plots in ggplot! see in Test 
knitr: 
  opts_chunk:
    dev: svg
    dev.args: { bg: "transparent" }

link-external-icon: false
link-external-newwindow: true

execute: 
  freeze: auto
